import { useMemo } from 'react';
import { useAuthStore } from '../store/authStore';

const DEFAULT_LABELS: Record<string, Record<string, string>> = {
    general: {
        sidebar_catalog: 'Serviços / Catálogo',
        sidebar_leads: 'Solicitações / Leads',
        sidebar_data: 'Operacional',
        catalog_title: 'Catálogo de Serviços',
        catalog_subtitle: 'Gerencie as opções oferecidas pelo assistente virtual',
        lead_singular: 'Lead',
        lead_plural: 'Leads',
        lead_title: 'Solicitações / Leads',
        item_singular: 'Item',
        item_plural: 'Itens',
        dash_stat_messages: 'Interações Totais',
        dash_stat_automation: 'IA / Automação',
        dash_stat_active: 'Em Atendimento',
        dash_stat_waiting: 'Fila de Espera',
    },
    security_academy: {
        sidebar_catalog: 'Cursos',
        sidebar_leads: 'Matrículas',
        sidebar_data: 'Academia',
        catalog_title: 'Catálogo de Cursos',
        catalog_subtitle: 'Gerencie os cursos de formação e especialização',
        lead_singular: 'Matrícula',
        lead_plural: 'Matrículas',
        lead_title: 'Matrículas / Alunos',
        item_singular: 'Curso',
        item_plural: 'Cursos',
    },
    medical: {
        sidebar_catalog: 'Procedimentos',
        sidebar_leads: 'Agendamentos',
        sidebar_data: 'Consultório',
        catalog_title: 'Tabela de Procedimentos',
        catalog_subtitle: 'Serviços médicos e consultas disponíveis',
        lead_singular: 'Paciente',
        lead_plural: 'Pacientes',
        lead_title: 'Pacientes / Agendamentos',
        item_singular: 'Procedimento',
        item_plural: 'Procedimentos',
        dash_stat_messages: 'Consultas Solicitadas',
        dash_stat_automation: 'Triagem Automática',
        dash_stat_active: 'Pacientes em Atendimento',
        dash_stat_waiting: 'Aguardando Recepção',
    },
    real_estate: {
        sidebar_catalog: 'Imóveis',
        sidebar_leads: 'Interessados',
        sidebar_data: 'Imobiliária',
        catalog_title: 'Carteira de Imóveis',
        catalog_subtitle: 'Gerencie os imóveis disponíveis para venda ou locação',
        lead_singular: 'Interessado',
        lead_plural: 'Interessados',
        lead_title: 'Interessados / Visitas',
        item_singular: 'Imóvel',
        item_plural: 'Imóveis',
        dash_stat_messages: 'Novos Interessados',
        dash_stat_automation: 'Qualificação de Leads',
        dash_stat_active: 'Visitas em Aberto',
        dash_stat_waiting: 'Fila de Contato',
    },
    education: {
        sidebar_catalog: 'Cursos',
        sidebar_leads: 'Alunos',
        sidebar_data: 'Escolar',
        catalog_title: 'Grade de Cursos',
        catalog_subtitle: 'Gerencie as turmas e cursos disponíveis',
        lead_singular: 'Aluno',
        lead_plural: 'Alunos',
        lead_title: 'Alunos / Matrículas',
        item_singular: 'Curso',
        item_plural: 'Cursos',
        dash_stat_messages: 'Inscrições em Curso',
        dash_stat_automation: 'Suporte Docente IA',
        dash_stat_active: 'Matrículas em Andamento',
        dash_stat_waiting: 'Fila de Secretaria',
    },
    legal: {
        sidebar_catalog: 'Serviços',
        sidebar_leads: 'Processos',
        sidebar_data: 'Escritório',
        catalog_title: 'Áreas de Atuação',
        catalog_subtitle: 'Gerencie os serviços jurídicos oferecidos',
        lead_singular: 'Cliente',
        lead_plural: 'Clientes',
        lead_title: 'Clientes / Processos',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    restaurant: {
        sidebar_catalog: 'Cardápio',
        sidebar_leads: 'Pedidos',
        sidebar_data: 'Delivery',
        catalog_title: 'Nosso Cardápio',
        catalog_subtitle: 'Gerencie os pratos e produtos disponíveis',
        lead_singular: 'Cliente',
        lead_plural: 'Clientes',
        lead_title: 'Clientes / Pedidos',
        item_singular: 'Produto',
        item_plural: 'Produtos',
    },
    sales: {
        sidebar_catalog: 'Produtos',
        sidebar_leads: 'Leads',
        sidebar_data: 'Comercial',
        catalog_title: 'Catálogo de Produtos',
        catalog_subtitle: 'Gerencie sua linha de produtos e estoque',
        lead_singular: 'Oportunidade',
        lead_plural: 'Oportunidades',
        lead_title: 'Oportunidades / Vendas',
        item_singular: 'Produto',
        item_plural: 'Produtos',
    },
    beauty: {
        sidebar_catalog: 'Serviços',
        sidebar_leads: 'Agendamentos',
        sidebar_data: 'Estética',
        catalog_title: 'Menu de Procedimentos',
        catalog_subtitle: 'Gerencie os horários e serviços de estética',
        lead_singular: 'Cliente',
        lead_plural: 'Clientes',
        lead_title: 'Clientes / Agendamentos',
        item_singular: 'Procedimento',
        item_plural: 'Procedimentos',
    },
    auto: {
        sidebar_catalog: 'Serviços',
        sidebar_leads: 'Ordens de Serviço',
        sidebar_data: 'Oficina',
        catalog_title: 'Serviços Automotivos',
        catalog_subtitle: 'Gerencie os serviços e peças da oficina',
        lead_singular: 'Proprietário',
        lead_plural: 'Proprietários',
        lead_title: 'Proprietários / Veículos',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    gym: {
        sidebar_catalog: 'Planos / Aulas',
        sidebar_leads: 'Alunos',
        sidebar_data: 'Academia',
        catalog_title: 'Grade de Modalidades',
        catalog_subtitle: 'Gerencie os planos de assinatura e aulas',
        lead_singular: 'Aluno',
        lead_plural: 'Alunos',
        lead_title: 'Alunos / Matrículas',
        item_singular: 'Modalidade',
        item_plural: 'Modalidades',
    },
    hotel: {
        sidebar_catalog: 'Quartos / Reservas',
        sidebar_leads: 'Hóspedes',
        sidebar_data: 'Hotelaria',
        catalog_title: 'Acomodações Disponíveis',
        catalog_subtitle: 'Gerencie os tipos de quartos e tarifas',
        lead_singular: 'Hóspede',
        lead_plural: 'Hóspedes',
        lead_title: 'Hóspedes / Reservas',
        item_singular: 'Quarto',
        item_plural: 'Quartos',
    },
    dental: {
        sidebar_catalog: 'Tratamentos',
        sidebar_leads: 'Pacientes',
        sidebar_data: 'Odontologia',
        catalog_title: 'Procedimentos Odontológicos',
        catalog_subtitle: 'Gerencie os serviços e especialidades',
        lead_singular: 'Paciente',
        lead_plural: 'Pacientes',
        lead_title: 'Pacientes / Agendamentos',
        item_singular: 'Tratamento',
        item_plural: 'Tratamentos',
    },
    veterinary: {
        sidebar_catalog: 'Serviços / Vacinas',
        sidebar_leads: 'Pets',
        sidebar_data: 'Clínica Vet',
        catalog_title: 'Cuidados Veterinários',
        catalog_subtitle: 'Gerencie os serviços para os pets',
        lead_singular: 'Pet',
        lead_plural: 'Pets',
        lead_title: 'Pets / Atendimento',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    accounting: {
        sidebar_catalog: 'Serviços',
        sidebar_leads: 'Clientes',
        sidebar_data: 'Contabilidade',
        catalog_title: 'Consultoria Contábil',
        catalog_subtitle: 'Gerencie os serviços fiscais e contábeis',
        lead_singular: 'Empresa',
        lead_plural: 'Empresas',
        lead_title: 'Empresas / Contratos',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    logistics: {
        sidebar_catalog: 'Rotas / Serviços',
        sidebar_leads: 'Cargas',
        sidebar_data: 'Logística',
        catalog_title: 'Soluções de Transporte',
        catalog_subtitle: 'Gerencie os serviços de frete e logística',
        lead_singular: 'Carga',
        lead_plural: 'Cargas',
        lead_title: 'Cargas / Entregas',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    it_services: {
        sidebar_catalog: 'Serviços / SLA',
        sidebar_leads: 'Tickets',
        sidebar_data: 'TI / Suporte',
        catalog_title: 'Soluções Tecnológicas',
        catalog_subtitle: 'Gerencie os serviços de suporte e infra',
        lead_singular: 'Ticket',
        lead_plural: 'Tickets',
        lead_title: 'Tickets / Incidentes',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    events: {
        sidebar_catalog: 'Pacotes / Buffet',
        sidebar_leads: 'Orçamentos',
        sidebar_data: 'Eventos',
        catalog_title: 'Guia de Eventos',
        catalog_subtitle: 'Gerencie os pacotes de festa e buffet',
        lead_singular: 'Cerimonial',
        lead_plural: 'Cerimoniais',
        lead_title: 'Noivos / Anfitriões',
        item_singular: 'Pacote',
        item_plural: 'Pacotes',
    },
    construction: {
        sidebar_catalog: 'Serviços / Obras',
        sidebar_leads: 'Projetos',
        sidebar_data: 'Engenharia',
        catalog_title: 'Portfólio de Obras',
        catalog_subtitle: 'Gerencie os serviços de construção e reforma',
        lead_singular: 'Obra',
        lead_plural: 'Obras',
        lead_title: 'Obras / Projetos',
        item_singular: 'Serviço',
        item_plural: 'Serviços',
    },
    agriculture: {
        sidebar_catalog: 'Insumos / Equipamentos',
        sidebar_leads: 'Produtores',
        sidebar_data: 'Agro',
        catalog_title: 'Catálogo do Campo',
        catalog_subtitle: 'Gerencie os produtos para agronegócio',
        lead_singular: 'Produtor',
        lead_plural: 'Produtores',
        lead_title: 'Produtores / Negócios',
        item_singular: 'Item',
        item_plural: 'Itens',
    },
    finance: {
        sidebar_catalog: 'Investimentos',
        sidebar_leads: 'Investidores',
        sidebar_data: 'Financeiro',
        catalog_title: 'Produtos Financeiros',
        catalog_subtitle: 'Gerencie as opções de crédito e investimento',
        lead_singular: 'Investidor',
        lead_plural: 'Investidores',
        lead_title: 'Investidores / Análise',
        item_singular: 'Produto',
        item_plural: 'Produtos',
    },
    insurance: {
        sidebar_catalog: 'Seguros / Apólices',
        sidebar_leads: 'Segurados',
        sidebar_data: 'Corretora',
        catalog_title: 'Portfólio de Seguros',
        catalog_subtitle: 'Gerencie os tipos de coberturas disponíveis',
        lead_singular: 'Segurado',
        lead_plural: 'Segurados',
        lead_title: 'Segurados / Cotações',
        item_singular: 'Seguro',
        item_plural: 'Seguros',
    }
};

export function useLabels() {
    const user = useAuthStore(state => state.user);

    const labels = useMemo(() => {
        const industry = user?.industryType || 'general';
        const industryLabels = DEFAULT_LABELS[industry] || {};
        const baseLabels = DEFAULT_LABELS.general;
        const custom = user?.customLabels || {};

        return {
            ...baseLabels,
            ...industryLabels,
            ...custom
        };
    }, [user?.industryType, user?.customLabels]);

    return labels;
}
